apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: off-site-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    labels: 
        app: off-site-ingress
spec:
    rules:
        - http:
            paths:
              - path: /database(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: edge-database-site
                    port: 
                      number: 80
              - path: /comp(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: edge-computational-site
                    port: 
                      number: 80
              - path: /regular(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: edge-regular-site
                    port: 
                      number: 80
              - path: /cloud(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: cloud-site
                    port: 
                      number: 80
    ingressClassName: nginx
